server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    include /etc/nginx/mime.types;

    location = /feed.xml {
        types { application/atom+xml xml; }
        default_type application/atom+xml;
    }

    location ~* \.m4a$ {
        types { audio/mp4 m4a; }
        default_type audio/mp4;
    }

    location / {
        try_files $uri =404;
    }
}
