apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: higgs
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
configMapGenerator:
  - name: higgs-feed
    files:
      - feed.xml
      - nginx/default.conf
